### ISSUE TITLE
"Copied to clipboard" message

### ISSUE THREAD

**Issue by Grizzly127** [Kompakkt/Repo#23]
### What? 

When clicking "embed in webpage" or "Copy ID", the message "Copied to clipboard" appears. After a few seconds it disappears. In semantic Kompakkt is the wrong font used (here is Helvetic neue used, but we should use open sans)

### Suggestion

left: wrong font, semantic Kompakkt, 
right: correct font and suggestion for less shadow
<img width="746" alt="Bildschirmfoto 2023-07-11 um 12 54 48" src="https://github.com/Kompakkt/Repo/assets/44752496/9e5d4a36-4e85-4b9d-976a-a5fa5e85fc28">

@HeyItsBATMAN @ZetOE @lozanaross

**Comment by lozanaross** [comment]
@Grizzly127 I think this is more relevant to Semantic Kompakkt than Kompakkt itself, so I would advise creating an issue in Gitlab and we can close this one here.
